version: "3.8"
services:
  frontend:
    build: ./frontend
    ports:
      - 3000:3000
  backend:
    build: ./backend
    ports:
      - 8080:8080
    environment:
      - PORT=8080
      - MYSQL_HOST=sql6.freesqldatabase.com
      - MYSQL_USER=sql6685110
      - MYSQL_PASSWORD=5zI79e5Acf
      - MYSQL_DB=sql6685110
      - SOLR_HOST=localhost
      - SOLR_PORT=8983
      - SOLR_CORE=mycore
    network_mode: "host"
    depends_on:
      - solr
  solr:
    image: solr:latest
    ports:
      - 8983:8983
    volumes:
      - ./conf:/opt/solr/server/solr/configsets/mycore_conf
    command: >
      bash -c "
      rm -rf /var/solr/data/mycore &&
      exec solr-foreground &
      sleep 5 &&
      bin/solr create -c mycore -d mycore_conf && wait
      "

